plugins {
    id 'eclipse'
    id 'maven-publish'
    // Apply the plugin. You can find the latest version at https://projects.neoforged.net/neoforged/ModDevGradle
    id 'net.neoforged.moddev.legacyforge' version '2.0.88'
    id 'dev._100media.gradleutils' version '1.+'
}

legacyForge {
    // Develop against MinecraftForge version 47.3.0 for 1.20.1 (the versions can be found at https://files.minecraftforge.net/)
    version = "${minecraft_version}-${forge_version}"

    // Validate AT files and raise errors when they have invalid targets
    // This option is false by default, but turning it on is recommended
    validateAccessTransformers = true

    runs {
        client {
            client()
            jvmArguments = ["-XX:+AllowEnhancedClassRedefinition"]
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mixin {
        add sourceSets.main, "${mod_id}.refmap.json"

        // Sets up the mixin config; this gets added to run configurations and the manifest in the final jar
        config "${mod_id}.mixins.json"


    }
    repositories {
        maven hundredMedia.get100MediaMaven()

        maven {
            name = 'Cursemaven'
            url = 'https://cursemaven.com'
            content {
                includeGroup 'curse.maven'
            }
        }
        maven {
            name = "SmartBrainLib (SBL) Maven Repo"
            url = "https://dl.cloudsmith.io/public/tslat/sbl/maven/"
        }
        maven {
            name "KosmX's maven"
            url 'https://maven.kosmx.dev/'
        }
    }

    dependencies {
        compileOnly 'org.jetbrains:annotations:26.0.2'
        annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
        compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
        implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.4.1"))
        // Capability Syncer
        modImplementation(jarJar("dev._100media.capabilitysyncer:capabilitysyncer:$capabilitysyncer_version"))

        // Suggestion Provider Fix
//    runtimeOnly fg.deobf("curse.maven:suggestion-provider-fix-469647:${suggestion_provider_fix_file_id}")
//    hundredMedia.addJarJarDep('software.bernie.geckolib:geckolib-forge-1.19', geckolib_version, geckolib_version_range, null, null)
//    hundredMedia.addJarJarDep('net.tslat.smartbrainlib:SmartBrainLib-forge-1.19.2', sbl_version, sbl_version_range, null, null)
//    hundredMedia.addJarJarDep('dev._100media.hundredmediageckolib:hundredmediageckolib', hundredmediageckolib_version, hundredmediageckolib_version_range)
//    hundredMedia.addJarJarDep('dev.kosmx.player-anim:player-animation-lib-forge',player_anim_version,player_anim_version_range,null,null)
        // 100 Media Morphs
//    hundredMedia.addJarJarDep('dev._100media.hundredmediamorphs:hundredmediamorphs', hundredmediamorphs_version, hundredmediamorphs_version_range, 'fat')
        modImplementation(jarJar("dev._100media.hundredmediaabilities:hundredmediaabilities:$hundredmediaabilities_version"))
//        hundredMedia.addJarJarDep('dev._100media.hundredmediaabilities:hundredmediaabilities', hundredmediaabilities_version, hundredmediaabilities_version_range, 'fat','1.19')

    }
    mods {
        testproject {
            sourceSet sourceSets.main
        }
    }

    def resourceTargets = ['META-INF/mods.toml', 'pack.mcmeta', "${mod_id}.mixins.json".toString()]
    def intoTargets = ["$rootDir/out/production/resources/", "$rootDir/out/production/${project.name}.main/", "$rootDir/bin/main/"]
    def replaceProperties = [mod_id: mod_id, mod_name: mod_name, mod_version: mod_version,
                             mod_authors: mod_authors, mod_description: mod_description,
                             minecraft_version_range: minecraft_version_range, forge_version_range: forge_version_range,
                             loader_version_range: loader_version_range]
    processResources {
        inputs.properties replaceProperties
        replaceProperties.put 'project', project

        filesMatching(resourceTargets) {
            expand replaceProperties
        }

        intoTargets.each { target ->
            if (file(target).exists()) {
                copy {
                    from(sourceSets.main.resources) {
                        include resourceTargets
                        expand replaceProperties
                    }
                    into target
                }
            }
        }
    }

}