# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.19.2
minecraft_version_range=[1.19,1.20)
forge_version=43.5.0
# The forge version range can use any version of forge or match the loader version range
forge_version_range=[41.1.0,)
# The loader version range can only be the major version of Forge/FML
loader_version_range=[41,)
parchment_minecraft_version=1.19.2
parchment_mappings_version=2022.11.27

mod_id=niconocolor
mod_name=NicoNoColor
mod_version=1.0.1
mod_base_package=com.nyfaria.niconocolor
mod_authors=Nyfaria
mod_description=Template

# Dependencies
mixin_version=0.8.5
capabilitysyncer_version=1.19-3.1.2
capabilitysyncer_version_range=[3.1.2,4.0.0)
suggestion_provider_fix_file_id=3832426
geckolib_version=3.1.38
geckolib_version_range=[3.1.38,4.0.0)
sbl_version=1.9
sbl_version_range=[1.9,1.10)
hundredmediageckolib_version=1.19.2-3.3.0
hundredmediageckolib_version_range=[3.2.5,4.0.0)
player_anim_version=1.0.2
player_anim_version_range=[1.0.2,1.0.3)
hundredmediamorphs_version=1.19.2-4.2.18
hundredmediamorphs_version_range=[4.2.17,5.0.0)
hundredmediaabilities_version=1.19-4.2.4
hundredmediaabilities_version_range=[4.2.4,4.3.0)